### 🔍 Get all contacts
GET http://localhost:8080/api/contacts

### 🔍 Get contact by ID — Happiness Igo
GET http://localhost:8080/api/contacts/68b7913dceb13f53e6d44fb8

### 🔍 Get contact by ID — David Panshank
GET http://localhost:8080/api/contacts/68b7913dceb13f53e6d44fba

### 🔍 Get contact by ID — James Ford
GET http://localhost:8080/api/contacts/68b7913dceb13f53e6d44fb9

### 🆕 Create a new contact
POST http://localhost:8080/api/contacts
Content-Type: application/json

{
  "firstName": "Nelson",
  "lastName": "Obi",
  "email": "nelsonobi@gmail.com",
  "favoriteColor": "White",
  "birthday": "2001-10-10"
  
}

### ✏️ Update contact — James Ford
PUT http://localhost:8080/api/contacts/68b7913dceb13f53e6d44fb9
Content-Type: application/json

{
  "firstName": "James",
  "lastName": "Ford",
  "email": "jamesbondvip1985@gmail.com",
  "favoriteColor": "Black",
  "birthday": "1985-12-16"
}

### ❌ Delete contact — Happiness Igo
DELETE http://localhost:8080/api/contacts/68c3084ee8b85253519d270b




### Get all books
GET http://localhost:8080/api/books

### Get a book by ID
GET http://localhost:8080/api/books/68cd7a61be99ede07597fefa

### Create a new book
POST http://localhost:8080/api/books
Content-Type: application/json

{
  "title": "Whispers in the Wind",
  "author": "Naomi Park",
  "genre": "Drama",
  "publishedYear": 1987,
  "pages": 213,
  "rating": 3.9,
  "available": true
}

### Update a book
PUT http://localhost:8080/api/books/68cdb73b3c5d54e81f9d972c
Content-Type: application/json

{
  "title": "Updated Title",
  "author": "Updated Author",
  "genre": "Drama",
  "publishedYear": 1990,
  "pages": 300,
  "rating": 4.5,
  "available": false
}
###
PUT http://localhost:8080/api/books/68cd7a61be99ede07597ff00
Accept: application/json
Content-Type: application/json
Cookie: connect.sid=s%3A4LSPW9UEKn5D2VHhYQq-7t2fdOB3CHcM.kwo3OFjZjb%2BgX5mVj9mra%2BiVqFJAw0ffUPcdk912Wsk

{
  "title": "The Last Cartographer",
  "author": "Aiden Clarke",
  "genre": "Adventure",
  "publishedYear": 1990,
  "pages": 398,
  "rating": 3.8,
  "available": true
}



### Delete a book
DELETE http://localhost:8080/api/books/68cdb73b3c5d54e81f9d972c
